### ISSUE TITLE
Integrate rsvg-rs into librsvg

### ISSUE THREAD

**Issue by federicomenaquintero** [selaux/rsvg-rs#8]
Hi!  I've started using rsvg-rs to write utilities for librsvg itself, starting with [rsvg-bench].  It is so nice to be able to do this in Rust, so *thanks* for writing rsvg-rs :)

During the Rust+GNOME hackfest in Berlin, @taye ported [rsvg-dimensions] to Rust; it also uses rsvg-rs.  

Both of those are utilities that should really live inside librsvg.  I'm thinking that it would be nice if librsvg provided its own binding to Rust.  Would you like to have rsvg-rs live within librsvg's repository?  It would then become easier to port librsvg's command-line utilities to Rust, since the binding would be right there.

[rsvg-bench]: https://gitlab.gnome.org/federico/rsvg-bench
[rsvg-dimensions]: https://gist.github.com/taye/a8cd2365828e76989f65cea086a23870

**Comment by selaux** [comment]
Sounds like a good idea. I'm also pro bindings directly from the `librsvg` project (I just created this one because there were none 🙂 ). How do you propose to move forward with this?

**Comment by selaux** [comment]
One thing to note might be that `rsvg-rs` currently is quite interwoven with [gtk-rs](http://gtk-rs.org/), because it uses its gobject-introspection bindings generator and libraries as dependencies. This results in `rsvg-rs` depending on specific versions of `glib` and `cairo-rs`, which in turn results in the need to update whenever those dependencies update in order to support the new version. So if you want to have a binding that is fully "independent", you might want to go another route. If you do so, you can just take over the rsvg crate and create your own bindings.

**Comment by federicomenaquintero** [comment]
May I invite you to take a look at https://gitlab.gnome.org/GNOME/librsvg/merge_requests/9 ? :smiley: We are considering using a Cargo workspace inside librsvg to make room for rsvg-rs and the actual binaries that will use it (rsvg-view-3, rsvg-bench, etc.).

I'm probably OK with having to do a librsvg release if the glib-rs/cairo-rs stuff needs to be updated.  This would involve setting up some policy for what sorts of API breaks are acceptable for the public Rust crate.

If you want to hang around the people who are working on this, we have `#rust` in `irc.gnome.org` :smile:

**Comment by federicomenaquintero** [comment]
@selaux, do you have an account in gitlab.gnome.org?  If not, could you please make one?  (You can use your Github credentials if you want.)

I've started a brainstorming issue there at https://gitlab.gnome.org/GNOME/librsvg/issues/207

**Comment by federicomenaquintero** [comment]
Closing as obsolete; librsvg provides its own Rust API now.
